---
abstract: 'CF conditioned by the value of another CF'
author:
  - 'Gérald Sédrati <gibus@easter-eggs.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ConditionalCustomFields
no_index:
  directory:
    - html
    - inc
    - static
    - xt
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/gibus/RT-Extension-ConditionalCustomFields
version: '1.14'
x_module_install_rtx_version: '0.43'
x_requires_rt: 4.2.0
x_rt_too_new: 5.1.0
